apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-getsecret
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://mariusciotir.github.io/k8s-getsecret/helm'
    chart: k8s-getsecret
    targetRevision: 0.1.0
    helm:
      values: |
        serviceAccount:
          name: "k8s-getsecret"
          roleName: "secret-reader"
          roleBindingName: "read-secrets-binding"
        global:
          namespaceOverride: "default"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
