apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-getsecret
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mariusciotir/k8s-getsecret.git'
    path: 'helm/k8s-getsecret'
    targetRevision: HEAD
    helm:
      values: |
        serviceAccount:
          name: "k8s-getsecret"
          roleName: "secret-reader"
          roleBindingName: "read-secrets-binding"
        global:
          namespaceOverride: "default"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
